version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab_belajar_oline
    volumes:
      - ./:/var/www/html
    ports:
      - "8005:80"
    depends_on:
      - db
    networks:
      - app-network  # Connect to the custom network

  db:
    image: mysql:8.0
    container_name: mysql_db_lab_belajar_oline
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab_belajar_online
    ports:
      - "3309:3306" 
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    networks:
      - app-network  # Connect to the custom network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_lab_belajar_online
    depends_on:
      - db
    ports:
      - "9005:80"  
    environment:
      PMA_HOST: db  # Nama service MySQL
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network  # Connect to the custom network
    restart: always

volumes:
  db_data:

networks:
  app-network:  # Define the custom network